### ISSUE TITLE
What the difference between  “.dependencies.json” and “.json”  in ./data?

### ISSUE THREAD

**Issue by HOIY14** [cyrillef/extract.autodesk.io#1]
Hi  cyrillef
I am trying to make this project work in my localhost to learn the forge service.
there is a problem when I uploading files.
In 'lmv-porject.js'    line 311~316

``` javascript
            function (err) { //- All tasks are done
                    if (err !== undefined && err !== null) {
                        console.log(err)  // I add one line here to see the err message
                        console.log ('Something wrong happened during upload') ;
                        callbacks2 (err, 3) ;
                        return ; `
```

the output windows shows

``` javascript
 async uploading(s)
async uploading 5681152-rst_basic_sample_projectrvt
5681152-rst_basic_sample_projectrvt
Failed to upload 5681152-rst_basic_sample_projectrvt
{ Error: ENOENT: no such file or directory, open 'D:\DB\coding\forgeweb\data\5681152-rst_basic_sample_projectrvt.json'
    at Error (native)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\DB\\coding\\forgeweb\\data\\5681152-rst_basic_sample_projectrvt.json' }
Something wrong happened during upload
```

I didn't know the difference between “.dependencies.json” and “.json” in ./data,
I am freshman in coding. Hope you can help.
Otherwise, is this project updated the live demo in http://extract.autodesk.io/?

**Comment by cyrillef** [comment]
Sorry for the delay in replying, I rewrote the sample to use the Forge v2 API so I do not need this dependencies file anymore. That file was to describe the various dependencies between files, for example an ipt being a dependency of an iam. In Forge v1, you had to describe the dependencies, in v2 just zip all files together, and submit the zip.
I also rewrote the sample using v2, so the error above should not happen any more. Let me know if you still got issue,
-cyrille
