### ISSUE TITLE
cannot GET /extracted/<x-x>.zip

### ISSUE THREAD

**Issue by gdemol** [cyrillef/extract.autodesk.io#10]
Hi, 

Not everything works as expected. I have two questions:

(1) I somehow I get the following error message when I try to extract a translated model:
![image](https://cloud.githubusercontent.com/assets/17804567/21260188/1a197ac6-c385-11e6-96ce-86603b0e39cf.png)

The contents of the directory /data/ gets cleaned up during the download of the viewer files at this point:
![image](https://cloud.githubusercontent.com/assets/17804567/21263831/36ecf3ee-c399-11e6-90e0-db1d045df73e.png)

After that, this happens again for a few more times. What is causing this?

(2) The model I upload is a model with another model as dependency. But in the viewer I only see one of the models. Why doesn't it show both of the models?

I used the following models: [testing models.zip](https://github.com/cyrillef/extract.autodesk.io/files/656965/testing.models.zip)

Thanks in advance!
Gerard

**Comment by gdemol** [comment]
Hi everyone,

Somehow I got this fixed installing bower again. Now everything works as expected.

Gerard

**Comment by cyrillef** [comment]
Hi,

ok cool - thx for letting me know
