### ISSUE TITLE
Is it possible to reconfigure the viewer it generates?

### ISSUE THREAD

**Issue by SelaOAL** [cyrillef/extract.autodesk.io#11]
After translation, you get a zip file with the bubbles and the viewer, is there a way to reconfigure this project so it will generates a viewer with our modifications (like extensions)?

**Comment by cyrillef** [comment]
Hi,

yes, create an extensions folder in the zip file and you put your extensions there. Next you need to modify the html file to load your extensions. If you got issue to do this, let me know,
