### ISSUE TITLE
Failed to upload model file!

### ISSUE THREAD

**Issue by pangubing** [cyrillef/extract.autodesk.io#13]
Hi,
Thank you for providing the code.
Following your instructions I installed this and set the parameters.
however when I try to upload a model I get these messages on the server side:

**Server listening on port 80
Token: {"access_token":"tNZaebzZ7hACve7PbwgeYmrHYJC6","token_type":"Bearer","exp
ires_in":86399}

POST partly_done 球面垫.SLDPRT 72422-SLDPRT
master: 72422-SLDPRT
Bucket created (or did exist already)!
async uploading(s)
async uploading 72422-SLDPRT
Failed to upload 72422-SLDPRT
Something wrong happened during upload**

any help will be appreciated.

**Comment by scott-duan71** [comment]
I met the same problem. Do you solve it? I will be very appreciated to get a solution!

**Comment by cyrillef** [comment]
Hi, sorry for the late reply. It seems to work fine for me, can you confirm? is you server Linux or OSX? did you set the directory write access to the folders?

**Comment by cyrillef** [comment]
fixed on my side
