### ISSUE TITLE
Where does the actual file upload happens?

### ISSUE THREAD

**Issue by SelaOAL** [cyrillef/extract.autodesk.io#14]
In submitProject(): https://github.com/cyrillef/extract.autodesk.io/blob/master/www/js/app.js#L129
I see that it just sends with an ajax request, an object with the file name and unique identifier but not the actual binary file.

In here: https://github.com/cyrillef/extract.autodesk.io/blob/master/www/js/upload-flow.js#L34 
there's r.upload(), is this the actual upload of the model?

Does it start to upload the file right as you press ok in the file chooser? 

Is there a way to give it a file path to upload instead of uploading with the form and file chooser?

(If some of those questions are irrelevant here, I posted them on [SO](http://stackoverflow.com/questions/41331270/questions-about-extract-autodesk-io))

**Comment by cyrillef** [comment]
I am using flow.js to upload files as multiple pieces, and reassemble them on the server.
The server endpoint is in https://github.com/cyrillef/extract.autodesk.io/blob/master/server/upload-flow.js where as the client process starts in https://github.com/cyrillef/extract.autodesk.io/blob/master/www/js/upload-flow.js#L36 

The upload will start immediately after file selection. For browser security reason, you need a human action to start an upload. There is no browser javascript code which will let you give a filepath on your disk to get it uploaded.
