### ISSUE TITLE
Interactive Parametrics?

### ISSUE THREAD

**Issue by bkwdesign** [cyrillef/extract.autodesk.io#15]
WOW!! This tool creates an amazing web presentation of models exported from Fusion

Are there plans to support a palette of user parameters that can be interacted with?

**Comment by cyrillef** [comment]
Hi

if you talk about the parametric modeling, the answer is no. Unfortunately, after translation from Fusion to Forge, all the parametric parameters are only fixed values since the Fusion engine is not there to evaluate them.
