### ISSUE TITLE
/api/projects shows 401 (Unauthorized)

### ISSUE THREAD

**Issue by tinygeek101** [cyrillef/extract.autodesk.io#27]
api's are not working

**Comment by CharlesCLLu** [comment]
I met the same error and couldn't find any solution from Google. Please help me. 
Thanks in advance.

**Comment by autodesk-adn** [comment]
could you please be more specific - the sample is running live and I just deployed it on heroku with no issue.

**Comment by CharlesCLLu** [comment]
After I traced the codes with Chrome DevTools for a long time, I found that it should be a reCAPTCHA 
Certification problem.

The 401 Unauthorized error disappeared when I filled my own site key and secret key respectively in [/www/index.html#L257](https://github.com/cyrillef/extract.autodesk.io/blob/01fea9e3b70b03f656ef04f37058af9b4fcde2ac/www/index.html#L257) and [/server/config.js#L41](https://github.com/cyrillef/extract.autodesk.io/blob/master/server/config.js#L41]).

**Comment by cyrillef** [comment]
Thx @CharlesCLLu , I added a readme setup instructions
