### ISSUE TITLE
How does the usage disclaimer in v4 of Forge Viewer affect this project and/or offline forge viewer support?

### ISSUE THREAD

**Issue by lukeify** [cyrillef/extract.autodesk.io#28]
I am developing an application which needs the ability to run the Autodesk Forge Viewer in an offline capacity. As of the [Autodesk Forge Viewer 4.0.0 release](https://developer.autodesk.com/en/docs/viewer/v2/overview/changelog/4.0/), an "Autodesk Forge Viewer Usage Limitations Disclaimer" has been added which states:

> The Autodesk Forge viewer can only be used to view files generated by Autodesk Forge services. The Autodesk Forge Viewer JavaScript must be delivered from an Autodesk hosted URL.

Where does this leave this project? Does this put offline Forge Viewer support in a grey area? Please consider making an exception for offline cases.

**Comment by autodesk-adn** [comment]
Hi, it is perfectly fine to download the bubble locally for viewing files when your internet connection is not working for example - The viewer application itself should be served from the Autodesk CDN as described in the viewer script header in your production/commercial release. It is acceptable to run the viewer locally for debugging and test propose.
