### ISSUE TITLE
Problem testing this github

### ISSUE THREAD

**Issue by ivanoterouvigo** [cyrillef/extract.autodesk.io#3]
Hi everybody!

I clone this github and load it.

I set credentials.js.

I try to upload a file and it doesn't do anything.

![extract_001](https://cloud.githubusercontent.com/assets/11814769/19676940/40f17804-9a97-11e6-80bf-3ba31f3d5eae.png)

Is this a old review? I need to use other branch?

Could you help me?

**Comment by cyrillef** [comment]
just made an upgrade, with new instructions. Let me know if any problem. it should also deploy on Heroku
-cyrille
