### ISSUE TITLE
I want to download a zip file on the explore file, but the file is 0kb, empty.

### ISSUE THREAD

**Issue by xiaocuihero** [cyrillef/extract.autodesk.io#4]

**Comment by afshinjafari** [comment]
Same problem here,
any solution yet?

**Comment by cyrillef** [comment]
just fixed it,
upgraded to forge v2

**Comment by xiaocuihero** [comment]
thanks, great job.

At 2016-11-25 00:52:59, "Cyrille" <notifications@github.com> wrote:


just fixed it,
upgraded to forge v2
