### ISSUE TITLE
miss /bower_components/

### ISSUE THREAD

**Issue by zhb123168** [cyrillef/extract.autodesk.io#7]
<script src="/bower_components/jquery/dist/jquery.js"></script>
    <link href="/bower_components/jquery-ui/themes/smoothness/jquery-ui.css" rel="stylesheet">
    <script src="/bower_components/jquery-ui/jquery-ui.js"></script>

**Comment by cyrillef** [comment]
it is working fine here with a fresh install
I mean bower install runs fine 
let me know what is your issue if I misunderstood the problem

**Comment by zhb123168** [comment]
It is my pleasure to receive your reply.

I met the problem is:
when I explore the projects, In the local can't browse.
1.、viewer3D.min.js:48 No viewer version specified, will implicitly use 2.10
2、viewer3D.min.js:1 THREE.DDSLoader.parse: Unsupported FourCC code  
3、viewer3D.min.js:1 THREE.DDSLoader.parse: Unsupported FourCC code  A
4、GET http://localhost:3000/1/0.pf 404 (Not Found)

**Comment by cyrillef** [comment]
Warning 1. is fine
2/3/4, I am not sure - which model is it so I can try myself?

**Comment by zhb123168** [comment]
c:\extract.autodesk.io>node start.js
c:\extract.autodesk.io\server\config.js:44
        config.bucket +=config.client_id.toLowerCase () ;

**Comment by zhb123168** [comment]
The explore model cann't be loader, the issues not be fix
1、No viewer version specified, will implicitly use 2.10
2、viewer3D.min.js:1 THREE.DDSLoader.parse: Unsupported FourCC code  A

**Comment by zhb123168** [comment]
Can you tell me your e-mail address?  i send the model to you, and i have  1G 3D-model-data want to test, Can you help me?

**Comment by zhb123168** [comment]
viewer3D.min.js:1 THREE.DDSLoader.parse: Unsupported FourCC code  A

**Comment by zhb123168** [comment]
192.168.229.1 - - [20/Nov/2016 02:51:08] code 404, message File not found
192.168.229.1 - - [20/Nov/2016 02:51:08] "GET /book/1.png HTTP/1.1" 404 -
192.168.229.1 - - [20/Nov/2016 02:51:08] "GET /book/1/book.svf HTTP/1.1" 200 -
192.168.229.1 - - [20/Nov/2016 02:51:08] code 404, message File not found
192.168.229.1 - - [20/Nov/2016 02:51:08] "GET /book/1/0.pf HTTP/1.1" 404 -
192.168.229.1 - - [20/Nov/2016 02:56:38] "GET /book/ HTTP/1.1" 200 -
192.168.229.1 - - [20/Nov/2016 02:56:38] "GET /book/style.css HTTP/1.1" 200 -
192.168.229.1 - - [20/Nov/2016 02:56:38] "GET /book/jquery.min.js HTTP/1.1" 200 -
192.168.229.1 - - [20/Nov/2016 02:56:38] "GET /book/jquery-ui.min.js HTTP/1.1" 200 -
192.168.229.1 - - [20/Nov/2016 02:56:38] "GET /book/three.min.js HTTP/1.1" 200 -
192.168.229.1 - - [20/Nov/2016 02:56:38] "GET /book/viewer3D.min.js HTTP/1.1" 200 -
192.168.229.1 - - [20/Nov/2016 02:56:39] "GET /book/lmvworker.min.js HTTP/1.1" 200 -
192.168.229.1 - - [20/Nov/2016 02:56:39] "GET /book/res/locales/zh-HANS/allstrings.json HTTP/1.1" 200 -
192.168.229.1 - - [20/Nov/2016 02:56:39] "GET /book/res/locales/en/allstrings.json HTTP/1.1" 200 -
192.168.229.1 - - [20/Nov/2016 02:56:39] "GET /book/res/environments/SharpHighlights_irr.logluv.dds HTTP/1.1" 200 -
192.168.229.1 - - [20/Nov/2016 02:56:39] "GET /book/res/environments/SharpHighlights_mipdrop.logluv.dds HTTP/1.1" 200 -
192.168.229.1 - - [20/Nov/2016 02:56:39] code 404, message File not found
192.168.229.1 - - [20/Nov/2016 02:56:39] "GET /book/1.png HTTP/1.1" 404 -
192.168.229.1 - - [20/Nov/2016 02:56:39] "GET /book/1/book.svf HTTP/1.1" 200 -
192.168.229.1 - - [20/Nov/2016 02:56:39] code 404, message File not found
192.168.229.1 - - [20/Nov/2016 02:56:39] "GET /book/1/0.pf HTTP/1.1" 404 -

**Comment by zhb123168** [comment]
miss <.pf> file

**Comment by cyrillef** [comment]
actually someone raised another issue which might be related. Checkout out: #9
I'll document it right now
Sorry for this -
